### ISSUE TITLE
レイアウト案検討

### ISSUE THREAD

**Issue by mapconcierge** [furuhashilab/aoyamavision2017#1]
ここに、作成したファイルや図などをメンバーと共有してください！

写真は重いので、別 Issue 立てたのでそこに格納してください。
https://github.com/furuhashilab/aoyamavision2017/issues/2

**Comment by nananairu** [comment]
<img width="516" alt="screen shot 2017-10-19 at 10 06 21" src="https://user-images.githubusercontent.com/26665840/31749475-33ccbd44-b4b5-11e7-9463-992460ac285a.png">

教室とラウンジのレイアウト使ってください

**Comment by mapconcierge** [comment]
＞  @nananairu ありがとう
イラレのファイルなども  zip 圧縮してここに置いておくとバックアップ代わりになります。

**Comment by mapconcierge** [comment]
＞ 各位：

写真置き場用の  Issue も作りました。
https://github.com/furuhashilab/aoyamavision2017/issues/2

**Comment by AyameO** [comment]
[f2.pdf](https://github.com/furuhashilab/aoyamavision2017/files/1405267/f2.pdf)

**Comment by AyameO** [comment]
![2017-10-23 4 36 38](https://user-images.githubusercontent.com/13360878/31865575-ce8ca580-b7ab-11e7-932c-a365f0f6de7f.png)

**Comment by Misa0716** [comment]
![zemi](https://user-images.githubusercontent.com/13146549/31870284-14fc6398-b7e8-11e7-9307-a3779fcedecc.jpg)

**Comment by maritaem** [comment]
![s__13385730](https://user-images.githubusercontent.com/20569769/31872756-715fa954-b7f9-11e7-9389-e818412141ff.jpg)

ラウンジについては現状維持を提案します。

**Comment by yuuuuka** [comment]
![image uploaded from ios](https://user-images.githubusercontent.com/13146558/31872857-45605a46-b7fa-11e7-9e3e-0f803b9dffec.jpg)

**Comment by aeri95** [comment]
![fullsizeoutput_b9f](https://user-images.githubusercontent.com/29531738/31875565-bdd545c2-b809-11e7-872e-a95f406e1c2e.jpeg)
ラウンジの壁際を中心として全体をそちらに向くように設定。
また現在はかなり広い空間を無駄にしているのでもっと自由に使ってよいのではと提案しました。

**Comment by AyameO** [comment]
[F2Lange.pdf](https://github.com/furuhashilab/aoyamavision2017/files/1409938/F2Lange.pdf)
現在状況、ラウンジ
机、80-90人分ぐらい
いす&ソファ、110人分ぐらい

**Comment by AyameO** [comment]
![2017-10-24 16 46 29](https://user-images.githubusercontent.com/13360878/31930504-ec3ceefc-b8da-11e7-92a9-0f9d9e0e86b2.png)

**Comment by AyameO** [comment]
[F2LangeAya.pdf](https://github.com/furuhashilab/aoyamavision2017/files/1426003/F2LangeAya.pdf)

**Comment by AyameO** [comment]
![2017-10-30 14 13 57](https://user-images.githubusercontent.com/13360878/32155740-9a948078-bd7c-11e7-8145-963631c41023.png)

**Comment by mapconcierge** [comment]
一度閉じます。
