### ISSUE TITLE
スクリーン近辺班　進捗状況（ナガノmaritaem・アンドウaeri95）

### ISSUE THREAD

**Issue by maritaem** [furuhashilab/aoyamavision2017#5]

**Comment by maritaem** [comment]
![802707084bcf5facee16f446d7194618ec000e06 68 1 12 2](https://user-images.githubusercontent.com/20569769/32428373-b5d57a86-c308-11e7-889c-916e709cb0f9.jpeg)
 
ウォールステッカー案
スクリーン、ホワイトボードの空きスペースに貼る

**Comment by aeri95** [comment]
![8f10a65ed50a92f9b05e5966aefe6c6db56e0e43](https://user-images.githubusercontent.com/29531738/32428730-9c169af6-c30a-11e7-8feb-624fc6dc6960.jpg)

**Comment by mapconcierge** [comment]
# 2017-11-06 の議論まとめ
---
* すのこの価格： 数百円〜数千円
* ぶら下げておくもの： 例えば文房具

**Comment by maritaem** [comment]
* どのようなスクリーンを採用するか

**Comment by aeri95** [comment]
#レイアウト事項

*入って左側ホワボ、右側スクリーン
　**スクリーンロールにするなら壁にはクライシスマッピングステッカー??
*下部に装飾すのこ: フック付き植物、LEDランプ、文房具をいれるラック

![img_5075](https://user-images.githubusercontent.com/29531738/32431395-ab86a010-c316-11e7-9249-51a25080025b.jpg)
現在のアイデア作図

**Comment by aeri95** [comment]
ロールスクリーンは無しの方向。よって世界地図も無し。

**Comment by maritaem** [comment]
![700eec7b-ea21-4c4f-b747-dd1afcc5f7a9](https://user-images.githubusercontent.com/20569769/32767241-d760d2d8-c955-11e7-9973-460cb60302d7.jpg)

11/13 時点の案です。

**Comment by mapconcierge** [comment]
90° 向きを変えた画像を置いておきます。
![32767241-d760d2d8-c955-11e7-9973-460cb60302d7](https://user-images.githubusercontent.com/416977/32819036-5478fb92-ca0a-11e7-8347-42faffd4f285.jpg)

**Comment by mapconcierge** [comment]
文句なしです！ 
とくに＞  @maritaem のセンスすばらしい。

完成形として閉じます。
