### ISSUE TITLE
工作スペース(大槻・加藤)タスク進歩状況

### ISSUE THREAD

**Issue by AyameO** [furuhashilab/aoyamavision2017#7]
[](url)
[kousakuROOM.pdf](https://github.com/furuhashilab/aoyamavision2017/files/1445229/kousakuROOM.pdf)
[kousakuROOM.pptx](https://github.com/furuhashilab/aoyamavision2017/files/1445230/kousakuROOM.pptx)
#1

**Comment by AyameO** [comment]
![2017-11-06 15 41 09](https://user-images.githubusercontent.com/13360878/32428421-f1768ac6-c308-11e7-82a8-cd72dc048bb8.png)

**Comment by yuuuuka** [comment]
katou

**Comment by yuuuuka** [comment]
＃３Dプリンタについて

-レーザーカッター（1.8×1.8）
-工作スペース自体に作業するスペースはないので、実際の作業はラウンジかくつろぎスペースなど

**Comment by AyameO** [comment]
https://www.google.co.jp/search?q=%E5%A3%81%E6%8E%9B%E3%81%91%E3%83%95%E3%83%83%E3%82%AF&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi4q5XuqLPXAhUPNbwKHchHCBAQ_AUICigB&biw=1440&bih=826#imgrc=OBVs09ktiycHzM:
![47409720](https://user-images.githubusercontent.com/13360878/32644815-5437d14e-c627-11e7-83af-caf6ade5e626.jpg)

**Comment by AyameO** [comment]
# 試作品
![img_4913](https://user-images.githubusercontent.com/13360878/32709852-126f84e4-c877-11e7-997d-0ec44b5413f9.jpg)

**Comment by mapconcierge** [comment]
ちゃんと垂直に撮影しましょう！こういうところを横着しない！！！ ＞ @AyameO

**Comment by mapconcierge** [comment]
![be610e6f-6851-4f3d-85bd-8dc3f96b8509](https://user-images.githubusercontent.com/416977/32819219-536b99c0-ca0b-11e7-8639-4f9395851b49.jpeg)

**Comment by mapconcierge** [comment]
トリミング後、コントラストなど画像補正

![32819219-536b99c0-ca0b-11e7-8639-4f9395851b49](https://user-images.githubusercontent.com/416977/32830384-54222334-ca38-11e7-82ff-6c4d80e57b85.jpeg)

**Comment by AyameO** [comment]
>@mapconcierge
かしこまりました！トリミング&補正ありがとうございました！

**Comment by mapconcierge** [comment]
このチームは提出物はクリアということで閉じます。

**Comment by AyameO** [comment]
> ＠mapconcierge
かしこまりました！
ありがとうございます！
